### ISSUE TITLE
Create clean .css instead of .scss.css

### ISSUE THREAD

**Issue by j15e** [hooktstudios/capistrano-recipes#4]
In utils/assets.rb we should simply strip the :ouput argument to get the file output more standard 

Now :

style.scss => style.scss.css

Should be :

style.scss => style.css

**Comment by prathe** [comment]
Sites touchés:

<del>./artdesanimaux/</del> Pas avec scss
<del>./hooktstudios2/</del> Pas avec scss
./maviemonmetier-wp/ OK
<del>./metrio-cascades/</del> Pas avec scss
<del>./riveringirard/</del> Pas avec scss

**Comment by prathe** [comment]
Finalement il y avait juste maviemonmetier-wp avec scss et capistrano-recipes.
